# Generated by Django 5.1.3 on 2024-11-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_categorymodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('file', models.FileField(upload_to='documents', verbose_name='Файл документа')),
                ('status', models.CharField(choices=[('not_processed', 'Не обработан'), ('processing', 'Обрабатывается'), ('success', 'Успешно обработан'), ('error', 'Ошибка обработки')], max_length=30, verbose_name='Статус обработки')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
