# Generated by Django 5.1.3 on 2024-11-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_documentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='status',
            field=models.CharField(choices=[('not_processed', 'Не обработан'), ('processing', 'Обрабатывается'), ('success', 'Успешно обработан'), ('error', 'Ошибка обработки')], default='not_processed', max_length=30, verbose_name='Статус обработки'),
        ),
    ]
