# Generated by Django 5.1.3 on 2024-11-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_documentmodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentmodel',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
    ]
