# Generated by Django 5.1.3 on 2024-11-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_documentmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmodel',
            name='file',
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='file_path',
            field=models.CharField(default='not_exist', max_length=1024, verbose_name='Файл документа'),
            preserve_default=False,
        ),
    ]
