# Generated by Django 5.1.3 on 2024-11-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_documentmodel_file_documentmodel_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='status',
            field=models.CharField(choices=[('not_processed', 'Не обработан'), ('processing', 'Обрабатывается'), ('success', 'Успешно обработан'), ('error', 'Ошибка обработки')], default='processing', max_length=30, verbose_name='Статус обработки'),
        ),
    ]
