# Generated by Django 5.1.3 on 2024-11-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_categorymodel_parent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categorymodel',
            index=models.Index(fields=['tree_id', 'level', 'title'], name='category_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='materialmodel',
            index=models.Index(fields=['price'], name='material_price_idx'),
        ),
    ]
