# Generated by Django 5.1.3 on 2024-11-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_categorymodel_category_sort_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmodel',
            name='file_path',
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='file',
            field=models.FileField(default=None, upload_to='documents', verbose_name='Файл документа'),
            preserve_default=False,
        ),
    ]
