# Generated by Django 5.1.3 on 2024-11-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_documentmodel_file_path_documentmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='Файл документа'),
        ),
    ]
