# Generated by Django 5.1.3 on 2024-11-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_documentmodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmodel',
            name='title',
        ),
    ]
