# Generated by Django 5.1.3 on 2024-11-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_documentmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Файл документа'),
        ),
    ]
