services:
    main-app:
        build:
            context: ..
            dockerfile: Dockerfile
        container_name: main-app
        ports:
            - ${DJANGO_PORT}:8000
        command: "sh entrypoint.sh gunicorn core.project.wsgi:application -c gunicorn.conf.py --bind 0.0.0.0:${DJANGO_PORT}"
        env_file:
            - ../.env
        depends_on:
            - postgres
        volumes:
            - like_s3:/app/documents

volumes:
    like_s3:
