services:
    celery-app:
        build:
            context: ..
            dockerfile: Dockerfile
        container_name: celery-app
        command: "celery -A core.project.celery worker --loglevel=info"
        env_file:
            - ../.env
        depends_on:
            - postgres
            - redis
