services:
    postgres:
        image: postgres:17
        container_name: postgres_db
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - base_postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        env_file:
            - ../.env

    redis:
        image: redis
        container_name: redis_db
        ports:
            - ${REDIS_PORT}:6379

volumes:
    base_postgres_data:
