services:
    postgres:
        image: postgres:17
        container_name: postgres_db
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        env_file:
            - ../.env
    minio:
        image: minio/minio:latest
        container_name: minio
        command: server /data --console-address :9001
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        ports:
            - 9000:9000
            - 9001:9001

    mc-init:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            sleep 5 &&\
            mc alias set $MINIO_ALIAS http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD &&\
            mc admin user add $MINIO_ALIAS $MINIO_USER_ACCESS_KEY $MINIO_USER_SECRET_KEY &&\
            mc admin policy attach $MINIO_ALIAS readwrite --user=$MINIO_USER_ACCESS_KEY &&\
            mc mb $MINIO_ALIAS/$MINIO_DOCUMENT_BUCKET
            "

    redis:
        image: redis
        container_name: redis_db
        ports:
            - ${REDIS_PORT}:6379
